name: "Code Analysis"

on:
  push:
    branches:
      - "main"
      - "master"
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
      - '**/*.yml'
      - '**/*.yaml'
      - '**/all'
  pull_request:
    branches:
      - "main"
      - "master"
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
      - '**/*.yml'
      - '**/*.yaml'
      - '**/all'

jobs:
  analyze-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.21.0'
          cache: false

      - name: Install golangci-lint
        run: |
          go get -u github.com/golangci/golangci-lint/cmd/golangci-lint

      - name: Run golangci-lint
        run: |
          golangci-lint run

  analyze-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up NodeJS
        uses: actions/setup-go@v4
        with:
          node-version: '18.15.0'

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint
