name: "Pipeline"

on:
  push:
    branches:
      - "main"
      - "master"

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.21.0'

      - name: Install Heroku CLI
        run: npm install -g heroku

      - name: Login to Heroku
        run: heroku login --email ${{ secrets.HEROKU_EMAIL }} --apikey ${{ secrets.HEROKU_API_KEY }}

      - name: Build and deploy to Heroku
        run: |
          heroku create
          go build -o myapp
          git add myapp
          git commit -m "Build binary"
          git push heroku main

      - name: Release to production
        run: heroku releases:deploy HEAD